#![deny(warnings)]
#![warn(clippy::pedantic)]
#![allow(
    clippy::write_with_newline,
    clippy::new_without_default,
    clippy::missing_errors_doc,
    clippy::missing_panics_doc,
    clippy::unnecessary_wraps,
    clippy::cast_precision_loss,
    rustdoc::private_intra_doc_links
)]

use lalrpop_util::lalrpop_mod;

pub mod ast;
pub mod bc;
pub mod rt;
#[allow(clippy::all, clippy::pedantic)]
pub mod stdlib;
pub mod tir;
pub mod utils;

lalrpop_mod!(
    #[allow(clippy::all, clippy::pedantic)]
    /// Parser generated by LALRPOP.
    pub grammar,
    "/ast/grammar.rs"
);

pub use ast::{parse, read};
pub use bc::{analyze, lower, optimize};
pub use tir::typecheck;
